let audioCtx=null;function initAudioOnFirstClick(){const e=()=>{if(!audioCtx)try{audioCtx=new(window.AudioContext||window.webkitAudioContext)}catch(n){}document.removeEventListener("click",e),document.removeEventListener("touchstart",e)};document.addEventListener("click",e),document.addEventListener("touchstart",e)}initAudioOnFirstClick();function beep(e,n,a,c=.18){if(!audioCtx)return;const o=audioCtx.createOscillator(),s=audioCtx.createGain();o.type="sine",o.frequency.value=e,s.gain.setValueAtTime(c,n),s.gain.exponentialRampToValueAtTime(.001,n+a),o.connect(s).connect(audioCtx.destination),o.start(n),o.stop(n+a)}function playOrderSound(e){const n={cafe:"sounds/cafe.mp3",delivery:"sounds/delivery.mp3",pickup:"sounds/pickup.mp3"},a=n[e]||n.pickup;try{const c=new Audio(a);c.volume=1,c.play().catch(()=>{})}catch(c){}}function playChatSound(){try{const e=new Audio("sounds/chat.mp3");e.volume=1,e.play().catch(()=>{})}catch(e){}}function playNotificationSound(){try{const e=new Audio("sounds/notification.mp3");e.volume=1,e.play().catch(()=>{})}catch(e){}}function playClosedSound(){if(!audioCtx)return;const e=audioCtx.currentTime;beep(360,e,.35,.09),beep(300,e+.28,.4,.08)}function ensureToastHost(){let e=document.getElementById("vtToastHost");return e||(e=document.createElement("div"),e.id="vtToastHost",e.className="vt-toast-host",document.body.appendChild(e)),e}function showToast(e,n="info",a=3200){const c=ensureToastHost(),o=document.createElement("div");o.className=`vt-toast vt-toast-${n} tap-fx`,o.textContent=e,c.appendChild(o),requestAnimationFrame(()=>o.classList.add("show")),setTimeout(()=>{o.classList.remove("show"),setTimeout(()=>o.remove(),300)},a)}function ensureModalHost(){let e=document.getElementById("vtModalHost");return e||(e=document.createElement("div"),e.id="vtModalHost",e.className="vt-modal-host",e.innerHTML=`
      <div class="cart-overlay vt-modal-overlay"></div>
      <div class="vt-modal-box">
        <p class="vt-modal-text" id="vtModalText"></p>
        <div class="vt-modal-actions" id="vtModalActions"></div>
      </div>`,document.body.appendChild(e)),e}function siteAlert(e,n="\u062A\u0645\u0627\u0645"){return new Promise(a=>{const c=ensureModalHost();c.querySelector("#vtModalText").textContent=e;const o=c.querySelector("#vtModalActions");o.innerHTML="";const s=document.createElement("button");s.className="glass-btn tap-fx",s.textContent=n,o.appendChild(s),c.classList.add("open");const d=()=>{c.classList.remove("open"),a(!0)};s.onclick=d,c.querySelector(".vt-modal-overlay").onclick=d})}function siteConfirm(e,n="\u062A\u0623\u0643\u064A\u062F",a="\u0625\u0644\u063A\u0627\u0621"){return new Promise(c=>{const o=ensureModalHost();o.querySelector("#vtModalText").textContent=e;const s=o.querySelector("#vtModalActions");s.innerHTML="";const d=document.createElement("button");d.className="glass-btn-secondary glass-btn tap-fx",d.textContent=a;const i=document.createElement("button");i.className="glass-btn tap-fx",i.textContent=n,s.appendChild(d),s.appendChild(i),o.classList.add("open");const r=f=>{o.classList.remove("open"),c(f)};i.onclick=()=>r(!0),d.onclick=()=>r(!1),o.querySelector(".vt-modal-overlay").onclick=()=>r(!1)})}function sitePrompt(e,{placeholder:n="",value:a="",okLabel:c="\u062A\u0623\u0643\u064A\u062F",cancelLabel:o="\u0625\u0644\u063A\u0627\u0621",inputType:s="text"}={}){return new Promise(d=>{const i=ensureModalHost();i.querySelector("#vtModalText").textContent=e;const r=i.querySelector("#vtModalActions"),f=i.querySelector(".vt-modal-box");r.innerHTML="";const l=document.createElement("input");l.type=s,l.className="vt-modal-input",l.placeholder=n,l.value=a,s==="number"&&(l.min="0",l.step="1",l.inputMode="numeric"),f.insertBefore(l,r);const u=document.createElement("button");u.className="glass-btn-secondary glass-btn tap-fx",u.textContent=o;const m=document.createElement("button");m.className="glass-btn tap-fx",m.textContent=c,r.appendChild(u),r.appendChild(m),i.classList.add("open"),setTimeout(()=>l.focus(),50);const v=p=>{l.remove(),i.classList.remove("open"),d(p)};m.onclick=()=>v(l.value),u.onclick=()=>v(null),l.addEventListener("keydown",p=>{p.key==="Enter"&&(p.preventDefault(),v(l.value))}),i.querySelector(".vt-modal-overlay").onclick=()=>v(null)})}function showClosedBanner(e){let n=document.getElementById("closedBanner");if(e){if(!n){n=document.createElement("div"),n.id="closedBanner",n.className="closed-banner";const a=(o,s)=>typeof t=="function"?t(o):s;n.innerHTML=`
        <button class="closed-banner-close tap-fx" id="closedBannerCloseX">\u2715</button>
        <div class="closed-banner-box">
          <div class="closed-icon-badge"><img class="emoji-gif" src="images/icons/emoji-closed.gif" alt="\u26D4" /></div>
          <h3 class="closed-banner-title">${a("closedTitleBig","\u0627\u0644\u0641\u0631\u0639 \u0645\u0642\u0641\u0648\u0644 \u062F\u0644\u0648\u0642\u062A\u064A")}</h3>
          <p class="closed-banner-subtitle">${a("closedSubtitle","\u0647\u0646\u0643\u0648\u0646 \u0641\u064A \u0627\u0633\u062A\u0642\u0628\u0627\u0644\u0643 \u062A\u0627\u0646\u064A \u0642\u0631\u064A\u0628 \u2014 \u062A\u0642\u062F\u0631 \u062A\u062E\u062A\u0627\u0631 \u0641\u0631\u0639 \u062A\u0627\u0646\u064A \u062F\u0644\u0648\u0642\u062A\u064A")}</p>
          <button class="glass-btn tap-fx" id="closedBannerChangeBranch">${a("closedChangeBranchBtn","\u0627\u062E\u062A\u064A\u0627\u0631 \u0641\u0631\u0639 \u062A\u0627\u0646\u064A")}</button>
        </div>`,document.body.appendChild(n),playClosedSound();const c=()=>{typeof goToBranchSelect=="function"&&goToBranchSelect()};document.getElementById("closedBannerCloseX").addEventListener("click",c),document.getElementById("closedBannerChangeBranch").addEventListener("click",c)}}else n&&n.remove()}
