// ============================================================
// قائمة أكواد الدول لخانة رقم الهاتف — الدول العربية الأول
// ============================================================
const COUNTRY_CODES = [
  { iso: "EG", dial: "20", flag: "🇪🇬", ar: "مصر", en: "Egypt" },
  { iso: "SA", dial: "966", flag: "🇸🇦", ar: "السعودية", en: "Saudi Arabia" },
  { iso: "AE", dial: "971", flag: "🇦🇪", ar: "الإمارات", en: "UAE" },
  { iso: "KW", dial: "965", flag: "🇰🇼", ar: "الكويت", en: "Kuwait" },
  { iso: "QA", dial: "974", flag: "🇶🇦", ar: "قطر", en: "Qatar" },
  { iso: "BH", dial: "973", flag: "🇧🇭", ar: "البحرين", en: "Bahrain" },
  { iso: "OM", dial: "968", flag: "🇴🇲", ar: "عُمان", en: "Oman" },
  { iso: "JO", dial: "962", flag: "🇯🇴", ar: "الأردن", en: "Jordan" },
  { iso: "LB", dial: "961", flag: "🇱🇧", ar: "لبنان", en: "Lebanon" },
  { iso: "IQ", dial: "964", flag: "🇮🇶", ar: "العراق", en: "Iraq" },
  { iso: "SY", dial: "963", flag: "🇸🇾", ar: "سوريا", en: "Syria" },
  { iso: "PS", dial: "970", flag: "🇵🇸", ar: "فلسطين", en: "Palestine" },
  { iso: "YE", dial: "967", flag: "🇾🇪", ar: "اليمن", en: "Yemen" },
  { iso: "LY", dial: "218", flag: "🇱🇾", ar: "ليبيا", en: "Libya" },
  { iso: "TN", dial: "216", flag: "🇹🇳", ar: "تونس", en: "Tunisia" },
  { iso: "DZ", dial: "213", flag: "🇩🇿", ar: "الجزائر", en: "Algeria" },
  { iso: "MA", dial: "212", flag: "🇲🇦", ar: "المغرب", en: "Morocco" },
  { iso: "SD", dial: "249", flag: "🇸🇩", ar: "السودان", en: "Sudan" },
  { iso: "SO", dial: "252", flag: "🇸🇴", ar: "الصومال", en: "Somalia" },
  { iso: "MR", dial: "222", flag: "🇲🇷", ar: "موريتانيا", en: "Mauritania" },
  { iso: "DJ", dial: "253", flag: "🇩🇯", ar: "جيبوتي", en: "Djibouti" },
  { iso: "KM", dial: "269", flag: "🇰🇲", ar: "جزر القمر", en: "Comoros" },
  { iso: "TR", dial: "90", flag: "🇹🇷", ar: "تركيا", en: "Turkey" },
  { iso: "US", dial: "1", flag: "🇺🇸", ar: "أمريكا", en: "United States" },
  { iso: "GB", dial: "44", flag: "🇬🇧", ar: "بريطانيا", en: "United Kingdom" },
  { iso: "CA", dial: "1", flag: "🇨🇦", ar: "كندا", en: "Canada" },
  { iso: "DE", dial: "49", flag: "🇩🇪", ar: "ألمانيا", en: "Germany" },
  { iso: "FR", dial: "33", flag: "🇫🇷", ar: "فرنسا", en: "France" },
  { iso: "IT", dial: "39", flag: "🇮🇹", ar: "إيطاليا", en: "Italy" },
  { iso: "ES", dial: "34", flag: "🇪🇸", ar: "إسبانيا", en: "Spain" },
  { iso: "NL", dial: "31", flag: "🇳🇱", ar: "هولندا", en: "Netherlands" },
  { iso: "GR", dial: "30", flag: "🇬🇷", ar: "اليونان", en: "Greece" },
  { iso: "IN", dial: "91", flag: "🇮🇳", ar: "الهند", en: "India" },
  { iso: "PK", dial: "92", flag: "🇵🇰", ar: "باكستان", en: "Pakistan" },
  { iso: "BD", dial: "880", flag: "🇧🇩", ar: "بنجلاديش", en: "Bangladesh" },
  { iso: "PH", dial: "63", flag: "🇵🇭", ar: "الفلبين", en: "Philippines" },
  { iso: "ID", dial: "62", flag: "🇮🇩", ar: "إندونيسيا", en: "Indonesia" },
  { iso: "MY", dial: "60", flag: "🇲🇾", ar: "ماليزيا", en: "Malaysia" },
  { iso: "CN", dial: "86", flag: "🇨🇳", ar: "الصين", en: "China" },
  { iso: "JP", dial: "81", flag: "🇯🇵", ar: "اليابان", en: "Japan" },
  { iso: "KR", dial: "82", flag: "🇰🇷", ar: "كوريا الجنوبية", en: "South Korea" },
  { iso: "RU", dial: "7", flag: "🇷🇺", ar: "روسيا", en: "Russia" },
  { iso: "AU", dial: "61", flag: "🇦🇺", ar: "أستراليا", en: "Australia" },
  { iso: "ZA", dial: "27", flag: "🇿🇦", ar: "جنوب أفريقيا", en: "South Africa" },
  { iso: "NG", dial: "234", flag: "🇳🇬", ar: "نيجيريا", en: "Nigeria" },
  { iso: "KE", dial: "254", flag: "🇰🇪", ar: "كينيا", en: "Kenya" },
  { iso: "ET", dial: "251", flag: "🇪🇹", ar: "إثيوبيا", en: "Ethiopia" },
  { iso: "BR", dial: "55", flag: "🇧🇷", ar: "البرازيل", en: "Brazil" },
];
